Feature/gift card
peaksoft-school/js6-giftlist pull request #2
Opened 2022-10-06 10:02 UTC by ErlanBakalov

gift card is ready ,
I have used styled components library

2022-10-06 11:55 UTC, aidanasm requested changes

2022-10-06 11:55 UTC, aidanasm commented on src/components/UI/GiftCard.jsx
> +   return (
тут только один стиль? а стиль второй карточки?

2022-10-06 11:55 UTC, aidanasm commented on src/components/UI/GiftCard.jsx
> +   vector,
не хватает пропса клика

2022-10-06 11:55 UTC, aidanasm commented on src/components/UI/GiftCard.jsx
> +      <MainCard>
высота карточки больше чем на фигме

2022-10-10 08:02 UTC, songhee24 requested changes

2022-10-10 08:02 UTC, songhee24 commented on src/components/UI/GiftCard.jsx
> +      setChange((prev) => !prev)
логика переключения стилей будет приходить из вне а значит просто булеан пропс который будет говорить какую именно карточку они хотят отобразить

2022-10-10 08:02 UTC, songhee24 commented on src/components/UI/GiftCard.jsx
> +            <button onClick={changeHandler}>onclick</button>
тут тоже нужно убрать эту кнопку

2022-10-10 12:49 UTC, songhee24 requested changes

2022-10-10 12:49 UTC, songhee24 commented on src/components/UI/GiftCard.jsx
> +   boolean,
Название не понятное что оно должно делать ?

2022-10-19 06:14 UTC, merged